swagger: "2.0"
info:
  description: "MNM 서비스의 RESTful API 문서입니다."
  version: "1.0.0"
  title: "Meet & Mate"
  contact:
    email: "songe08@gmial.com"
  license:
    name: "GPL 3.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "petstore.swagger.io"
basePath: "/v2"
tags:
  - name: "house"
    description: "하우스에 관련한 모든 정보"
  - name: "rule"
    description: "공동 생활 규약에 관련한 모든 정보"
  - name: "role"
    description: "하우스내 일일 역할에 대한 모든 정보"
  - name: "evaluation"
    description: "하우스 사용자 평점에 대한 모든 정보"
  - name: "auth"
    description: "사용자 인증에 대한 모든 정보"
  - name: "chatting"
    description: "사용자 채팅에 대한 모든 정보"
  - name: "chatting room"
    description: "사용자 채팅방에 대한 모든 정보"
  - name: "profile"
    description: "사용자 프로필에 대한 모든 정보"
  - name: "matching"
    description: "사용자 매칭에 대한 모든 정보"
  - name: "residenceinfo"
    description: "사용자 거주에 대한 모든 정보"
schemes:
  - "http"

paths:
  /auth/join:
    post:
      tags:
        - "auth"
      summary: "회원가입하기"
      operationId: "join"
      responses:
        "200":
          description: "OK"
  /auth/login:
    post:
      tags:
        - "auth"
      summary: "로그인하기"
      operationId: "login"
      responses:
        "200":
          description: "OK"
  /auth/remove:
    delete:
      tags:
        - "auth"
      summary: "탈퇴하기"
      operationId: "remove"
      responses:
        "200":
          description: "OK"
  /user/evaluation:
    post:
      tags:
        - "evaluation"
      summary: "평가 등록하기"
      operationId: "createEvaluation"
      parameters:
        - name: "X-AUTH-TOKEN"
          in: "header"
          required: true
          type: "string"
      responses:
        "200":
          description: "OK"
  /user/evaluation/profile/{id}:
    get:
      tags:
        - "evaluation"
      summary: "평가 정보 조회하기"
      operationId: "getProfileComment"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "number"
          format: "int32"
      responses:
        "200":
          description: "OK"
  /user/evaluation/{id}:
    get:
      tags:
        - "evaluation"
      summary: "미평가자 조회하기"
      operationId: "getDoNotEvaluation"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "number"
          format: "int32"
        - name: "X-AUTH-TOKEN"
          in: "header"
          required: true
          type: "string"
      responses:
        "200":
          description: "OK"
  /user/house/:
    get:
      tags:
        - "house"
      summary: "속해 있는 하우스 목록 조회하기"
      operationId: "readAllHouse"
      parameters:
        - name: "X-AUTH-TOKEN"
          in: "header"
          required: true
          type: "string"
      responses:
        "200":
          description: "OK"
    post:
      tags:
        - "house"
      summary: "하우스 생성하기"
      operationId: "createHouse"
      parameters:
        - name: "X-AUTH-TOKEN"
          in: "header"
          required: true
          type: "string"
      responses:
        "200":
          description: "OK"
  /user/house/{id}:
    get:
      tags:
        - "house"
      summary: "하우스 조회하기"
      operationId: "readHouse"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "number"
          format: "int32"
      responses:
        "200":
          description: "OK"
    patch:
      tags:
        - "house"
      summary: "하우스 내용 수정하기"
      operationId: "editHouse"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "number"
          format: "int32"
      responses:
        "200":
          description: "OK"
    delete:
      tags:
        - "house"
      summary: "하우스 삭제하기"
      operationId: "exitHouse"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "number"
          format: "int32"
        - name: "X-AUTH-TOKEN"
          in: "header"
          required: true
          type: "string"
      responses:
        "200":
          description: "OK"
  /user/role:
    post:
      tags:
        - "role"
      summary: "역할 등록하기"
      operationId: "createRole"
      responses:
        "200":
          description: "OK"
  /user/role/house/{id}:
    get:
      tags:
        - "role"
      summary: "하우스에 대항 역할 정보 조회하기"
      operationId: "readRoles"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "number"
          format: "int32"
      responses:
        "200":
          description: "OK"
  /user/role/{id}:
    patch:
      tags:
        - "role"
      summary: "역할 정보 수정하기"
      operationId: "updateRole"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "number"
          format: "int32"
      responses:
        "200":
          description: "OK"
    delete:
      tags:
        - "role"
      summary: "역할 삭제하기"
      operationId: "deleteRole"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "number"
          format: "int32"
      responses:
        "200":
          description: "OK"
  /user/rule:
    post:
      tags:
        - "rule"
      summary: "규약 등록하기"
      operationId: "createRule"
      responses:
        "200":
          description: "OK"
  /user/rule/house/{id}:
    get:
      tags:
        - "rule"
      summary: "하우스에 대한 규약 조회하기"
      operationId: "readRules"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "number"
          format: "int32"
      responses:
        "200":
          description: "OK"
  /user/rule/{id}:
    patch:
      tags:
        - "rule"
      summary: "규약 수정하기"
      operationId: "updateRule"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "number"
          format: "int32"
      responses:
        "200":
          description: "OK"
    delete:
      tags:
        - "rule"
      summary: "규약 삭제하기"
      operationId: "deleteRule"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "number"
          format: "int32"
      responses:
        "200":
          description: "OK"
  /user/chatting/{cid}:
    get:
      tags:
        - "chatting"
      summary: "채팅 방에 따른 채팅 정보 조회"
      operationId: "getChattingList"
      parameters:
        - name: "cid"
          in: "path"
          required: true
          type: "number"
          format: "int64"
        - name: "X-AUTH-TOKEN"
          in: "header"
          required: true
          type: "string"
      responses:
        "200":
          description: "OK"
  /user/chatting/{cid}/accept:
    post:
      tags:
        - "chatting"
      summary: "하우스 메이트 승인"
      operationId: "acceptRequest"
      parameters:
        - name: "cid"
          in: "path"
          required: true
          type: "number"
          format: "int64"
        - name: "X-AUTH-TOKEN"
          in: "header"
          required: true
          type: "string"
      responses:
        "200":
          description: "OK"
  /user/chatting/{cid}/decline:
    post:
      tags:
        - "chatting"
      summary: "하우스 메이트 거절"
      operationId: "declineRequest"
      parameters:
        - name: "cid"
          in: "path"
          required: true
          type: "number"
          format: "int64"
        - name: "X-AUTH-TOKEN"
          in: "header"
          required: true
          type: "string"
      responses:
        "200":
          description: "OK"
  /user/chatting/{cid}/request:
    post:
      tags:
        - "chatting"
      summary: "하우스 메이트 요청"
      operationId: "sendRequest"
      parameters:
        - name: "cid"
          in: "path"
          required: true
          type: "number"
          format: "int64"
        - name: "X-AUTH-TOKEN"
          in: "header"
          required: true
          type: "string"
      responses:
        "200":
          description: "OK"
  /user/chattingRoom:
    get:
      tags:
        - "chatting room"
      summary: "채팅방 목록 조회하기"
      operationId: "getChattingRoomList"
      parameters:
        - name: "X-AUTH-TOKEN"
          in: "header"
          required: true
          type: "string"
      responses:
        "200":
          description: "OK"
  /user/chattingRoom/exist:
    get:
      tags:
        - "chatting room"
      summary: "채팅방 존재 여부 조회하기"
      operationId: "isExisted"
      parameters:
        - name: "senderUid"
          in: "query"
          required: true
          type: "number"
          format: "int64"
        - name: "receiverUid"
          in: "query"
          required: true
          type: "number"
          format: "int64"
      responses:
        "200":
          description: "OK"
  /user/chattingRoom/make:
    post:
      tags:
        - "chatting room"
      summary: "채팅방 생성하기"
      operationId: "makeChattingRoom"
      responses:
        "200":
          description: "OK"
  /user/chattingRoom/{cid}/latest:
    get:
      tags:
        - "chatting room"
      summary: "가장 최근의 채팅방 정보 조회하기"
      operationId: "getChattingRoomLatest"
      parameters:
        - name: "cid"
          in: "path"
          required: true
          type: "number"
          format: "int64"
        - name: "X-AUTH-TOKEN"
          in: "header"
          required: true
          type: "string"
      responses:
        "200":
          description: "OK"
  /user/image/:
    get:
      tags:
        - "profile"
      summary: "사용자 이미지 조회하기"
      operationId: "getImage"
      parameters:
        - name: "imagePath"
          in: "query"
          required: true
          type: "string"
      responses:
        "200":
          description: "OK"
  /user/matchinginfo/:
    put:
      tags:
        - "matching"
      summary: "매칭정보 수정하기"
      operationId: "updateMatchingInfo"
      parameters:
        - name: "X-AUTH-TOKEN"
          in: "header"
          required: true
          type: "string"
      responses:
        "200":
          description: "OK"
    post:
      tags:
        - "matching"
      summary: "매칭정보 등록하기"
      operationId: "addMatchingInfo"
      parameters:
        - name: "X-AUTH-TOKEN"
          in: "header"
          required: true
          type: "string"
      responses:
        "200":
          description: "OK"
  /user/matchinginfo/{uid}:
    get:
      tags:
        - "matching"
      summary: "매칭정보 조회하기"
      operationId: "getMatchingInfo"
      parameters:
        - name: "uid"
          in: "path"
          required: true
          type: "number"
          format: "int64"
      responses:
        "200":
          description: "OK"
    delete:
      tags:
        - "matching"
      summary: "매칭정보 삭제하기"
      operationId: "deleteMatchingInfo"
      parameters:
        - name: "uid"
          in: "path"
          required: true
          type: "string"
        - name: "X-AUTH-TOKEN"
          in: "header"
          required: true
          type: "string"
      responses:
        "200":
          description: "OK"
  /user/profile/:
    put:
      tags:
        - "profile"
      summary: "프로필 정보 수정하기"
      operationId: "updateProfile"
      parameters:
        - name: "image"
          in: "query"
          required: true
          type: "string"
        - name: "name"
          in: "query"
          required: true
          type: "string"
        - name: "sex"
          in: "query"
          required: true
          type: "string"
        - name: "age"
          in: "query"
          required: true
          type: "number"
          format: "int32"
        - name: "score"
          in: "query"
          required: true
          type: "number"
          format: "int32"
        - name: "description"
          in: "query"
          required: true
          type: "string"
        - name: "X-AUTH-TOKEN"
          in: "header"
          required: true
          type: "string"
      responses:
        "200":
          description: "OK"
    post:
      tags:
        - "profile"
      summary: "프로필 정보 등록하기"
      operationId: "addProfile"
      parameters:
        - name: "X-AUTH-TOKEN"
          in: "header"
          required: true
          type: "string"
      responses:
        "200":
          description: "OK"
    patch:
      tags:
        - "profile"
      summary: "프로필 정보 갱신하기"
      operationId: "editProfile"
      parameters:
        - name: "image"
          in: "query"
          type: "string"
        - name: "name"
          in: "query"
          type: "string"
        - name: "sex"
          in: "query"
          type: "string"
        - name: "age"
          in: "query"
          type: "number"
          format: "int32"
        - name: "score"
          in: "query"
          type: "number"
          format: "int32"
        - name: "X-AUTH-TOKEN"
          in: "header"
          required: true
          type: "string"
      responses:
        "200":
          description: "OK"
    delete:
      tags:
        - "profile"
      summary: "프로필 삭제하기"
      operationId: "deleteProfile"
      parameters:
        - name: "X-AUTH-TOKEN"
          in: "header"
          required: true
          type: "string"
      responses:
        "200":
          description: "OK"
  /user/profile/{uid}:
    get:
      tags:
        - "profile"
      summary: "사용자 프로필 조회하기"
      operationId: "getProfile"
      parameters:
        - name: "uid"
          in: "path"
          required: true
          type: "number"
          format: "int64"
      responses:
        "200":
          description: "OK"
  /user/residenceinfo/:
    post:
      tags:
        - "residenceinfo"
      summary: "거주 정보 등록하기"
      operationId: "addResidenceInfo"
      responses:
        "200":
          description: "OK"
  /user/residenceinfo/{uid}:
    get:
      tags:
        - "residenceinfo"
      summary: "거주정보 조회하기"
      operationId: "getResidenceInfo"
      parameters:
        - name: "uid"
          in: "path"
          required: true
          type: "number"
          format: "int64"
      responses:
        "200":
          description: "OK"
    put:
      tags:
        - "residenceinfo"
      summary: "거주정보 수정하기"
      operationId: "updateResidenceInfo"
      parameters:
        - name: "uid"
          in: "path"
          required: true
          type: "number"
          format: "int64"
      responses:
        "200":
          description: "OK"
    delete:
      tags:
        - "residenceinfo"
      summary: "거주정보 삭제하기"
      operationId: "deleteResidenceInfo"
      parameters:
        - name: "uid"
          in: "path"
          required: true
          type: "number"
          format: "int64"
      responses:
        "200":
          description: "OK"

externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
